print("joao lucas")
#2. Faça um programa que imprima o produto dos valores 30 e 27.
print(30*27)
#3. Faça um programa que imprima a média aritmética entre os números 5, 8, 12.
print((5+8+12)/3)
#4. Faça um programa que leia e imprima um número inteiro.
numero = input("12:")
#5. Faça um programa que leia dois números reais e os imprima.
numero = real(input('digite um numero real'))
print(numero)













