#1. Faça um programa que imprima o seu nome.
print("joao lucas")
#2. Faça um programa que imprima o produto dos valores 30 e 27.
print(30*27)
#3. Faça um programa que imprima a média aritmética entre os números 5, 8, 12.
print((5+8+12)/3)
#4. Faça um programa que leia e imprima um número inteiro.
numero = input("12:")
#5. Faça um programa que leia dois números reais e os imprima.
num1 = input('digite num1: ')
num2 = input('digite num2: ')
print(num1)
print(num2)
#6. Faça um programa que leia um número inteiro e imprima o seu
#   antecessor e o seu sucessor.
#7. Faça um programa que leia o nome o endereço e o telefone de
#   um cliente e ao final, imprima esses dados.
nome = input(str('digite seu nome:  '))
endereço = input(str('digite seu endereço:  '))
telefone = input(str('digite seu telefone:  '))
print(nome)
print(endereço)
print(telefone)
#8. Faça um programa que leia dois números inteiros e imprima a
#   subtração deles.
num1 = input(int('digite num1'))
num2 = input(int('digite num2'))
soma = num1 + num2
print(num1 + num2)


  


















